"""Candidate generation funnel — propose brands BEFORE fusion scores them.

Evidence used to feed candidate scores directly, so every brand a detector
happened to name entered the ranking. That lets a flood of weak generated names
dilute a strong winner and makes the fusion search space unbounded. This module
adds an explicit generation stage:

    signals -> candidate generator -> top-K -> (fusion) -> ranked verdict

Candidate generators (all cheap, all local to already-computed signals):
    * OCR / ASR alias match against the brand catalog
    * brand-resolved logo detections
    * product-index retrieval matches (score = similarity)

`select_candidates` then bounds what fusion sees to the generator's top-K while
PROTECTING brands that carry direct evidence (logo / speech / product), so a
real sighting can never be gated out by a low generator score. Absence is not a
candidate: brands with no evidence are simply never generated.
"""

from __future__ import annotations

from typing import Dict, List, Optional, Sequence

from src.brand_catalog import match_brand

# Families that constitute direct, non-derived evidence for a brand. A brand
# carrying any of these is always retained by the funnel regardless of its
# generator rank.
DIRECT_FAMILIES = {"logo", "speech", "product"}

# Generator prior weights (a brand can be generated by several sources; the
# strongest prior is kept and the rest add a small corroboration bonus).
_GEN_SCORES = {
    "logo": 0.80,
    "ocr": 0.65,
    "speech": 0.60,
    "product": 0.55,
}


def generate_candidates(
    *,
    logo_brands: Sequence[str] = (),
    ocr_texts: Sequence[str] = (),
    speech_mentions: Sequence = (),
    product_matches: Optional[Sequence[dict]] = None,
    top_k: int = 0,
) -> List[dict]:
    """Rank candidate brands from raw signals (descending score).

    Args:
        logo_brands: brands resolved on logo detections.
        ocr_texts: raw OCR strings (matched against the catalog).
        speech_mentions: strings or {"brand": ...} dicts from ASR.
        product_matches: [{"brand", "similarity"}, ...] from product retrieval.
        top_k: when > 0, truncate to the top K candidates.

    Returns:
        [{"candidate", "score", "sources": [str, ...]}, ...]
    """
    scores: Dict[str, float] = {}
    sources: Dict[str, set] = {}

    def bump(brand: Optional[str], source: str, value: float) -> None:
        if not brand:
            return
        # strongest single prior wins; extra independent sources corroborate.
        prior = _GEN_SCORES.get(source, value)
        base = prior if source != "product" else max(prior, min(1.0, value))
        if brand not in scores:
            scores[brand] = base
        elif source not in sources[brand]:
            scores[brand] = min(1.0, scores[brand] + 0.05)
        sources.setdefault(brand, set()).add(source)

    for b in logo_brands:
        bump(b, "logo", _GEN_SCORES["logo"])
    for text in ocr_texts:
        bump(match_brand(text or ""), "ocr", _GEN_SCORES["ocr"])
    for mention in speech_mentions:
        brand = mention.get("brand") if isinstance(mention, dict) else str(mention)
        bump(match_brand(brand or "") or (brand if brand in _known() else None),
             "speech", _GEN_SCORES["speech"])
    for m in product_matches or ():
        bump(m.get("brand"), "product", float(m.get("similarity", 0.0)))

    ranked = sorted(
        (
            {"candidate": b, "score": round(s, 4), "sources": sorted(sources.get(b, set()))}
            for b, s in scores.items()
        ),
        key=lambda c: (-c["score"], c["candidate"]),
    )
    return ranked[:top_k] if top_k and top_k > 0 else ranked


def _known() -> set:
    from src.brand_catalog import BRAND_CATALOG

    return set(BRAND_CATALOG.keys())


def select_candidates(
    ledger: Dict[str, List[dict]],
    generated: List[dict],
    top_k: int,
) -> Dict[str, List[dict]]:
    """Restrict a ledger to the generated top-K (+ direct-evidence brands).

    top_k <= 0 disables gating and returns the ledger unchanged. Brands with a
    DIRECT_FAMILIES item are always kept, so gating can never drop a genuine
    logo/speech/product sighting — it only trims weak, derived-only names.
    """
    if top_k is None or top_k <= 0:
        return ledger
    allowed = {c["candidate"] for c in generated[:top_k]}
    protected = {
        b
        for b, items in ledger.items()
        if any(it.get("family") in DIRECT_FAMILIES for it in items)
    }
    return {
        b: items
        for b, items in ledger.items()
        if b in allowed or b in protected
    }
